// client/src/pages/Changelog.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { REST_URL } from 'src/env';
	import iconAdd from 'src/assets/icons/changelog/add.svg';
	import iconDelete from 'src/assets/icons/changelog/delete.svg';
	import iconLower from 'src/assets/icons/changelog/lower.svg';
	import iconRaise from 'src/assets/icons/changelog/raise.svg';

	// TODO: Use OpenAPI generation

	interface Log {
		action: string;
		from?: number;
		to?: number;
		timestamp: string;
		level: any;
		list: any[];
	}

	const dict = {
		ADD: 'Added',
		MOVE: 'Moved',
		DELETE: 'Deleted',
	};

	let changelog: Log[] = [];

	onMount(async () => {
		const res = await fetch(new URL('/changelog', REST_URL).toString());
		changelog = await res.json();
	});

	// Undo the log changes to restore list before changes
	// TODO: Maybe store this in the database changelog instead of recalculating every time?
	function calcBefore(entry: Log): any[] {
		const list = entry.list.slice();
		list.splice(entry.to - 1, 1);
		list.splice(entry.from - 1, 0, entry.level);
		return list;
	}

	function getIcon(entry: Log): string {
		switch (entry.action) {
			case 'ADD':
				return iconAdd;
			case 'DELETE':
				return iconDelete;
			case 'MOVE':
				return entry.to > entry.from ? iconLower : iconRaise;
		}
		return '';
	}
</script>

<div class="page-changelog">
	<h1>Changelog</h1>
	<ol role="list" class="log">
		{#each changelog as entry}
			{@const before = calcBefore(entry)}
			<li class="entry">
				<p class="date mono">
					{new Date(entry.timestamp).toLocaleDateString()}
				</p>
				<div class="summary">
					<p>
						{dict[entry.action]}
						<a href={`/level/${entry.level.id}`}>{entry.level.name}</a>
					</p>
				</div>
				<div class="changes">
					{#each before.slice(entry.from - 2, entry.from + 1) as level, index}
						<div class="before" class:self={index === 1}>
							<p>{level.name}</p>
						</div>
						<p class="before-rank" class:self={index === 1}>
							#{index + entry.from - 1}
						</p>
					{/each}
					<div class="icon">
						<img src={getIcon(entry)} alt="change" />
					</div>
					{#each entry.list.slice(entry.to - 2, entry.to + 1) as level, index}
						<p class="after-rank" class:self={index === 1}>
							#{index + entry.to - 1}
						</p>
						<div class="after" class:self={index === 1}>
							<p>{level.name}</p>
						</div>
					{/each}
				</div>
			</li>
		{/each}
	</ol>
</div>

<style lang="scss">
	@use 'src/styles/color';
	@use 'src/styles/screen';

	@include screen.xl {
		.page-changelog {
			display: grid;
			grid-template-columns: calc(8rem + 4px) 1fr calc(8rem + 4px);
			padding-inline: calc(6rem + 1px);

			h1,
			.log {
				grid-column: 2 / span 1;
			}

			h1 {
				margin-block: 6rem;
			}

			.log {
				display: flex;
				flex-direction: column;
				gap: 3rem;

				.entry {
					max-width: 72rem;
					display: grid;
					grid-template-columns: 1fr 2fr 3fr;
					align-items: start;

					.date {
						color: rgba(color.$on-background, 0.4);
					}

					.summary {
						display: flex;

						&::after {
							content: '';
							flex: 1;
							border-top: 1px solid color.$on-background;
							position: relative;
							margin-left: 1.25rem;
							align-self: center;
						}

						a {
							color: inherit;
							border-bottom: 1px solid color.$on-background;
						}
					}

					.changes {
						display: grid;
						grid-template-columns: 1fr max-content 1.5rem max-content 1fr;
						grid-auto-rows: max-content;
						grid-auto-flow: column;
						align-items: center;
						gap: 1rem 0.5rem;
						color: rgba(color.$on-background, 0.4);
						border-color: rgba(color.$on-background, 0.4);

						.before,
						.after {
							white-space: nowrap;
						}

						.before {
							grid-column: 1;
							display: flex;
							justify-content: end;
							position: relative;

							&::before {
								content: '';
								flex: 1;
								border-top: 1px solid;
								position: relative;
								margin-right: 1.25rem;
								align-self: center;
							}
						}

						.before:not(:first-child) {
							&::after {
								content: '';
								border-left: 1px solid;
								position: absolute;
								left: 0;
								bottom: 50%;
								top: calc(-50% - 1rem);
							}
						}

						.before-rank {
							grid-column: 2;
						}

						.icon {
							grid-column: 3;
							grid-row: span 3;
							align-self: center; // TODO: edge-case: changes at rank 1
						}

						.after-rank {
							grid-column: 4;
							text-align: end;
						}

						.after {
							grid-column: 5;
						}

						.self {
							color: color.$on-background;
							border-color: color.$on-background;
						}
					}
				}
			}
		}
	}
</style>

// client/src/components/changelog.tsx
import { Component, createMemo, For, JSX, Show } from 'solid-js';
import { Changelog, Level, LevelWithRank } from 'src/generated/openapi';

import iconAdd from 'src/assets/icons/changelog/add.svg';
import iconDelete from 'src/assets/icons/changelog/delete.svg';
import iconNoChange from 'src/assets/icons/changelog/no_change.svg';
import iconLower from 'src/assets/icons/changelog/lower.svg';
import iconRaise from 'src/assets/icons/changelog/raise.svg';

import './changelog.scss';

interface ListChangeColumnProps {
	after: boolean;
	action: Changelog['action'];
	rank: number;
	list: Level[];
}

const ListChangeColumn: Component<ListChangeColumnProps> = function (props) {
	const slice = createMemo<Array<LevelWithRank | undefined>>(() => {
		const listWithRank: Array<LevelWithRank | undefined> = props.list.map((lvl, i) => ({
			...lvl,
			rank: i + 1,
		}));
		if ((!props.after && props.action === 'add') || (props.after && props.action === 'archive')) {
			listWithRank.splice(props.rank - 1, 0, undefined);
		}
		const start = Math.max(props.rank - 2, 0);
		const end = Math.min(props.rank, props.list.length) + 1;
		return listWithRank.slice(start, end);
	});

	const classList = createMemo(() => ({ after: props.after, before: !props.after }));

	const self = (rank: number) => {
		if (props.after && props.action === 'archive') return false;
		if (!props.after && props.action === 'add') return false;
		return rank === props.rank;
	};

	return (
		<>
			{/* Show "Top of List" */}
			<Show when={props.rank === 1}>
				<div class="top" classList={classList()}>
					<p class="type-label-md">Top of List</p>
				</div>
			</Show>
			{/* Show Levels / Leap */}
			<For each={slice()}>
				{(level) => (
					<Show keyed when={level} fallback={<div class="leap" classList={classList()} />}>
						{(level) => (
							<div classList={{ self: self(level.rank), ...classList() }}>
								<div class="stripe" />
								<p class="level">{level.name}</p>
								<p class="rank mono">#{level.rank}</p>
							</div>
						)}
					</Show>
				)}
			</For>
			{/* Show "End of List" */}
			<Show when={(self(props.rank) ? props.rank : props.rank - 1) === props.list.length}>
				<div class="bottom" classList={classList()}>
					<p class="type-label-md">End of List</p>
				</div>
			</Show>
		</>
	);
};

interface ListChangeProps {
	action: Changelog['action'];
	from?: number;
	to?: number;
	level: Level;
	before: Level[];
	after: Level[];
}

export const ListChange: Component<ListChangeProps> = function (props) {
	const icon = createMemo<string>(() => {
		switch (props.action) {
			case 'add':
				return iconAdd;
			case 'archive':
				return iconDelete;
			case 'move':
				if ((props.to as number) === (props.from as number)) return iconNoChange;
				return (props.to as number) > (props.from as number) ? iconLower : iconRaise;
		}
	});

	return (
		<div class="list-change">
			<ListChangeColumn
				after={false}
				action={props.action}
				rank={(props.action === 'add' ? props.to : props.from) as number}
				list={props.before}
			/>
			<div class="icon">
				<img src={icon()} alt="change" />
			</div>
			<ListChangeColumn
				after={true}
				action={props.action}
				rank={(props.action === 'archive' ? props.from : props.to) as number}
				list={props.after}
			/>
		</div>
	);
};
